export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="tadebastiani"

plugins=(git tmux)

# Plugins configurations
export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_AUTOCONNECT=false
export ZSH_TMUX_AUTOQUIT=false

source $ZSH/oh-my-zsh.sh

# User configuration

# Aliases

alias code=vscodium
alias cd-projects="cd ~/Documentos/Projects"
alias vim="nvim"
